fixes #56 (Do Not Merge)
tessel/t2-start pull request #166
Opened 2017-07-04 07:40 UTC by brihijoshi

Still in progress which fixes #56. Added Linux Terminal images and icon.

2017-07-05 12:09 UTC, mittalshravika commented
The commits made by me(@mittalshravika) are for fixes #158. Added certain links for the reader to connect with the cli documentation.

2017-07-21 08:45 UTC, brihijoshi commented
@Frijol PR ready for review.

2017-07-24 20:49 UTC, Frijol commented
This PR would also be better as two PR's!

2017-07-24 21:00 UTC, Frijol requested changes
Fix for #56 is ready to go; fix for #158 needs a bit of work

2017-07-24 21:00 UTC, Frijol commented on blinky.md
> +Have a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#starting-projects) to explore `t2 init` command.
One of the most important design factors in Tessel's first run is that getting started doesn't take very long. This means the design and instructions are intentionally very streamlined and uncluttered– making https://github.com/tessel/t2-start/issues/158 a design challenge! We need to make sure that the information is available, but does not feel like an extra step users have to take before moving on.

With this current suggestion, going to look at the docs is a part of the main instructions– but it's not actually necessary that they do it before moving forward. How can we make the distinction clear?

In some places, we use italic text to provide further information:
![screen shot 2017-07-24 at 1 53 49 pm](https://user-images.githubusercontent.com/454690/28544309-930af5fa-7077-11e7-87c5-0bb9f1c900c5.png)

In other places, we call out additional non-necessary exercises with bold bonus annotation:
![screen shot 2017-07-24 at 1 54 37 pm](https://user-images.githubusercontent.com/454690/28544350-a931ad4c-7077-11e7-94f2-1ce142264dcd.png)

Do either of these approaches make sense for adding in extra docs links? Or, do we need to add a new design element, like a callout box or one of these?
![helptext box](https://www.smashingmagazine.com/wp-content/uploads/2011/11/skype1.jpg)

I think personally I'd try italic text and see if that works; you are welcome to experiment with other ideas too.

2017-07-24 21:00 UTC, Frijol commented on blinky.md
> +Have a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#starting-projects) to explore `t2 init` command.
copy edit, should read: "to explore the `t2 init` command`

2017-07-24 21:00 UTC, Frijol commented on wifi.md
> +To explore more options available for `t2 wifi`, take a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#using-wifi).
See note on `t2 init`

2017-07-24 21:00 UTC, Frijol commented on wifi.md
> +Have a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#updating-tessel-2-on-board-osfirmware) to get more information on updations.
See note on `t2 init`

2017-07-24 21:14 UTC, mittalshravika commented on blinky.md
> +Have a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#starting-projects) to explore `t2 init` command.
Sure. Will make the changes.

2017-07-25 07:06 UTC, mittalshravika commented
Made the changes accordingly.

2017-07-29 00:47 UTC, Frijol requested changes
Looks good, just a capitalization nitpick

2017-07-29 00:47 UTC, Frijol commented on blinky.md
> +_Have a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#starting-projects) to explore the `t2 init` command._
"CLI" should be capitalized

2017-07-29 00:47 UTC, Frijol commented on wifi.md
> +_To explore more options available for the `t2 wifi` command, take a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#using-wifi)._
CLI caps again

2017-07-29 00:47 UTC, Frijol commented on wifi.md
> +_Have a look at [the cli docs](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#updating-tessel-2-on-board-osfirmware) to get more information on updations._
CLI caps again

2017-07-29 06:52 UTC, mittalshravika commented
Capitalized CLI as suggested.

2017-07-29 21:49 UTC, Frijol approved these changes

2017-07-29 21:56 UTC, Frijol commented
Looks great! Merging.

2017-07-29 21:56 UTC, merged